# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    # Prevent from doubling up while making multiple deployments at the same time
    concurrency: ci-${{github.ref}}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure Node
      uses: actions/setup-node@v4
      with:
        node-version: '20.13.1'

    - name: Install
      run: |
        rm -rf node_modules/ package-lock.json
        npm install --include=optional  # Force install optional deps
        npm ci
        npm run build --if-present
      # npm test

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist
        branch: gh-pages
        
